### ISSUE TITLE
efbconnect

### ISSUE THREAD

**Issue by rick69er** [ollyau/EFBConnect#7]
im trying to connect to my tablet in hype h160 i cant add any websites i did once along time ago but cant now?

**Comment by ollyau** [comment]
This GitHub repository pertains to EFB Connect, an application that sends position, attitude, and traffic information from Microsoft Flight Simulator to ForeFlight (an EFB running on a physical iPad).  The software here is unaffiliated with Hype Performance Group and is completely unrelated to the H160 addon.

Hype Performance Group appears to have a contact form on their website at https://www.hypeperformancegroup.com/pages/contact-us if you want to reach someone who may be able to help you with your issues.

**Comment by rick69er** [comment]
I guess you didnt understand what i was saying its not a physical ipad its the ipade in the helo an efbSent from my iPhoneOn Apr 23, 2024, at 11:56 PM, Orion Lyau ***@***.***> wrote:﻿
This GitHub repository pertains to EFB Connect, an application that sends position, attitude, and traffic information from Microsoft Flight Simulator to ForeFlight (an EFB running on a physical iPad).  The software here is unaffiliated with Hype Performance Group and is completely unrelated to the H160 addon.
Hype Performance Group appears to have a contact form on their website at https://www.hypeperformancegroup.com/pages/contact-us if you want to reach someone who may be able to help you with your issues.

**Comment by ollyau** [comment]
I understand that you're looking for assistance with the tablet in the virtual cockpit of your H160 addon -- what I'm saying is that this page is **_not related_** to the tablet in the H160 addon.  As I personally do not have a copy of the H160 addon, and since I am not affiliated with Hype Performance Group (the developers of the H160 addon for MSFS), I'm unable to help you.

This page is for a desktop application (an .exe file that you launch) that I've created, called EFB Connect, which is intended for use with ForeFlight (a specific EFB app that runs on a physical iPad).  It runs entirely outside Microsoft Flight Simulator, and there is no component in the virtual cockpit of any aircraft.

Again, I recommend that you ask Hype Performance Group for assistance, as they created the tablet inside the H160 helicopter's virtual cockpit.
